apiVersion: batch/v1
kind: Job
metadata:
  name: write-to-disk
spec:
  template:
    spec:
      containers:
      - name: count
        image: busybox
        args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$i: $(date)" >> /var/log/1.log;
            echo "$(date) INFO $i" >> /var/log/2.log;
            i=$((i+1));
            sleep 1;
          done
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        persistentVolumeClaim:
          claimName: ssd-data
      restartPolicy: Never
  backoffLimit: 4
