apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-data-restore-volume
spec:
  storageClassName: faster
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: restored-pd-ssd
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-data-restore
spec:
  storageClassName: faster
  volumeName: ssd-data-restore-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi